version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'restaurant_finder'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - 5432:5432
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - redis
      - postgres
    ports:
      - 3000:3000

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    env_file:
      - .env.testing
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - postgres
      - redis
    command: >
      sh -c "
        ./node_modules/.bin/knex migrate:latest
        ${COMMAND}
      "